#!/usr/bin/env python3
"""Regenerate KPV village summaries and the master README from folder contents."""

import argparse
import os
import sys
from datetime import datetime
from pathlib import Path

from anthropic import Anthropic
from dotenv import load_dotenv

MODEL = "claude-sonnet-4-6"
AUTOGEN_HEADER = "<!-- Auto-generated by generate.py - do not edit manually -->\n\n"

READABLE_EXTS = {".md", ".txt", ".csv"}
BINARY_EXTS = {".pdf", ".xlsx", ".xls", ".docx", ".doc", ".pptx", ".ppt"}
SKIP_FILES = {"village-summary.md", ".gitkeep", ".DS_Store"}

VILLAGES = [
    {"name": "Waihi", "code": "WAI", "id": "KPV-25-001", "folder": "waihi"},
    {"name": "Papamoa", "code": "PAP", "id": "KPV-25-002", "folder": "papamoa"},
    {"name": "Hamilton", "code": "HAM", "id": "KPV-25-003", "folder": "hamilton"},
    {"name": "Cromwell", "code": "CRO", "id": "KPV-25-004", "folder": "cromwell"},
]

REPO_ROOT = Path(__file__).resolve().parent


VILLAGE_PROMPT = """You are generating a project summary for a retirement village development.

Village: {village_name} ({village_code}) - Project ID: {village_id}

Below is all available project content for this village, including file names and readable text content. Summarise the current state of this village project into a structured markdown document.

Include the following sections if information is available:
- Project overview (one paragraph)
- Current phase and status
- Key dates and milestones
- Budget and financial notes
- Consenting and design status
- Construction status
- Sales and occupancy status
- Outstanding items or risks
- File index (list all files found, grouped by phase folder)

If a section has no available information, omit it rather than leaving it blank.

Use plain markdown. No em dashes - use hyphens. Use "and" not "&".
Keep language professional and concise.

CONTENT:
{content}
"""

README_PROMPT = """You are generating a master knowledge base summary for KPV (Karaka Pines Villages), a multi-village retirement development portfolio in New Zealand.

Below are the current village summaries for all active villages. Generate a master README.md that gives a portfolio-level overview.

Include:
- KPV portfolio overview (two to three sentences)
- Village status table (village name, project ID, code, current phase, one-line status)
- Per-village section with a brief summary pulled from each village summary
- Last updated timestamp

Use plain markdown. No em dashes - use hyphens. Use "and" not "&".
Keep it concise - this is an index, not a report.

VILLAGE SUMMARIES:
{summaries}
"""


def collect_village_content(village_folder: Path) -> tuple[str, int]:
    """Walk a village folder and return (context_string, file_count)."""
    if not village_folder.exists():
        return "", 0

    readable_blocks = []
    binary_files = []
    all_files_by_phase: dict[str, list[str]] = {}
    file_count = 0

    for path in sorted(village_folder.rglob("*")):
        if not path.is_file():
            continue
        if path.name in SKIP_FILES:
            continue

        rel = path.relative_to(village_folder)
        phase = rel.parts[0] if len(rel.parts) > 1 else "(root)"
        all_files_by_phase.setdefault(phase, []).append(str(rel))
        file_count += 1
        print(f"  indexed: {rel}")

        ext = path.suffix.lower()
        if ext in READABLE_EXTS:
            try:
                text = path.read_text(encoding="utf-8", errors="replace")
            except Exception as exc:
                print(f"  WARN: could not read {rel}: {exc}")
                continue
            readable_blocks.append(f"### FILE: {rel}\n\n{text}\n")
        elif ext in BINARY_EXTS:
            binary_files.append(str(rel))
        else:
            binary_files.append(str(rel))

    index_lines = ["## File index\n"]
    for phase in sorted(all_files_by_phase):
        index_lines.append(f"\n**{phase}**")
        for f in all_files_by_phase[phase]:
            index_lines.append(f"- {f}")
    index_block = "\n".join(index_lines) if all_files_by_phase else "(no files)"

    parts = [index_block]
    if readable_blocks:
        parts.append("\n\n## Readable content\n\n" + "\n\n".join(readable_blocks))
    if binary_files:
        parts.append(
            "\n\n## Binary files (filenames only, contents not read)\n\n"
            + "\n".join(f"- {f}" for f in binary_files)
        )

    return "\n".join(parts), file_count


def empty_village_summary(village: dict) -> str:
    return (
        AUTOGEN_HEADER
        + f"# {village['name']} ({village['code']}) - {village['id']}\n\n"
        "No content is available yet for this village. Add files to the phase "
        "subfolders and re-run `python generate.py` to regenerate this summary.\n"
    )


def generate_village_summary(client: Anthropic, village: dict) -> tuple[str, int]:
    village_folder = REPO_ROOT / village["folder"]
    print(f"\n=== {village['name']} ({village['code']}) ===")
    content, count = collect_village_content(village_folder)

    if count == 0:
        print(f"  no files found - writing minimal summary")
        return empty_village_summary(village), 0

    prompt = VILLAGE_PROMPT.format(
        village_name=village["name"],
        village_code=village["code"],
        village_id=village["id"],
        content=content,
    )

    print(f"  calling API for {count} file(s)...")
    response = client.messages.create(
        model=MODEL,
        max_tokens=4096,
        messages=[{"role": "user", "content": prompt}],
    )
    body = response.content[0].text
    return AUTOGEN_HEADER + body + "\n", count


def generate_master_readme(client: Anthropic, any_content: bool) -> str:
    blocks = []
    for village in VILLAGES:
        summary_path = REPO_ROOT / village["folder"] / "village-summary.md"
        if not summary_path.exists():
            continue
        text = summary_path.read_text(encoding="utf-8")
        blocks.append(f"## {village['name']} ({village['code']}) - {village['id']}\n\n{text}\n")

    if not blocks or not any_content:
        stamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        table = "\n".join(
            f"| {v['name']} | {v['id']} | {v['code']} | - | No content yet |"
            for v in VILLAGES
        )
        return (
            AUTOGEN_HEADER
            + "# KPV Knowledge Base\n\n"
            "Living knowledge base for the Karaka Pines Villages development portfolio. "
            "Village summaries and this README are regenerated from folder contents by `generate.py`.\n\n"
            "## Villages\n\n"
            "| Village | Project ID | Code | Current phase | Status |\n"
            "|---|---|---|---|---|\n"
            f"{table}\n\n"
            "Add files to the phase subfolders under each village and run `python generate.py` to refresh.\n\n"
            f"---\n_Last generated: {stamp}_\n"
        )

    prompt = README_PROMPT.format(summaries="\n\n".join(blocks))

    print("\n=== master README ===")
    print("  calling API...")
    response = client.messages.create(
        model=MODEL,
        max_tokens=4096,
        messages=[{"role": "user", "content": prompt}],
    )
    body = response.content[0].text
    stamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    return AUTOGEN_HEADER + body + f"\n\n---\n_Last generated: {stamp}_\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate KPV village summaries.")
    parser.add_argument(
        "--village",
        help="Regenerate only this village folder (e.g. waihi). Master README is still refreshed.",
    )
    args = parser.parse_args()

    load_dotenv(REPO_ROOT / ".env")
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("ERROR: ANTHROPIC_API_KEY not found. Copy .env.example to .env and set the key.")
        return 1

    client = Anthropic(api_key=api_key)

    if args.village:
        selected = [v for v in VILLAGES if v["folder"] == args.village]
        if not selected:
            valid = ", ".join(v["folder"] for v in VILLAGES)
            print(f"ERROR: unknown village '{args.village}'. Valid options: {valid}")
            return 1
    else:
        selected = VILLAGES

    processed = []
    total_files = 0
    for village in selected:
        summary, count = generate_village_summary(client, village)
        out_path = REPO_ROOT / village["folder"] / "village-summary.md"
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(summary, encoding="utf-8")
        processed.append(f"{village['name']} ({count} files)")
        total_files += count
        print(f"  wrote {out_path.relative_to(REPO_ROOT)}")

    any_content = any(
        (REPO_ROOT / v["folder"]).exists()
        and any(
            p.is_file() and p.name not in SKIP_FILES
            for p in (REPO_ROOT / v["folder"]).rglob("*")
        )
        for v in VILLAGES
    )
    readme = generate_master_readme(client, any_content)
    (REPO_ROOT / "README.md").write_text(readme, encoding="utf-8")
    print("  wrote README.md")

    print("\nDone.")
    print(f"Villages processed: {', '.join(processed)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
